services:
  - type: web
    name: women-go-for-peace
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn women_go_for_peace.wsgi:application
    repo: https://github.com/AlMezui241/women_go_for_peace
    branch: main
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "women-go-for-peace.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://women-go-for-peace.onrender.com,https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: women-go-for-peace-db
          property: connectionString
databases:
  - name: women-go-for-peace-db
    engine: postgres
    plan: free